name: Bug report
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen? What happened instead?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps/config to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Include relevant logs (with secrets removed)
      render: shell
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Adapter version
      description: Docker tag or GitHub Release version
      placeholder: 0.3.1
    validations:
      required: false
